name: GFSLT-VLP
## configured for volta cluster
data:
  train_label_path: ./data/Phonexi-2014T/labels.train
  dev_label_path: ./data/Phonexi-2014T/labels.dev
  test_label_path: ./data/Phonexi-2014T/labels.test
  img_path: ../../PHOENIX-2014-T-release-v3/PHOENIX-2014-T/features/fullFrame-210x260px/
  max_length: 500
training:
  wandb: disabled # online or disabled
  scale_embedding: False
  tokens: False
model:
  tokenizer: pretrain_models/MBart_trimmed
  transformer: pretrain_models/mytran
  visual_encoder: pretrain_models/MBart_trimmed
  sign_proj: True
