name: GFSLT-VLP
## configured for volta cluster
data:
  train_label_path: ./data/Phonexi-2014T/labels.train
  dev_label_path: ./data/Phonexi-2014T/labels.dev
  test_label_path: ./data/Phonexi-2014T/labels.test
  img_path: /hpctmp/e0724993/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/features/fullFrame-210x260px
  max_length: 300
training:
  wandb: disabled # online or disabled
  scale_embedding: False
model:
  tokenizer: /hpctmp/e0724993/pretrain_models/MBart_proun
  transformer:  /hpctmp/e0724993/pretrain_models/MBart_proun
  visual_encoder: /hpctmp/e0724993/pretrain_models/mytran
  sign_proj: True
